services:
    nginx:
        build: ./docker/nginx
        volumes:
            # - "./nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
            # - ./www:/usr/share/nginx/html
            # - /Users/funkyi/Desktop/Projects/Me/mssp-extensions:/usr/share/nginx/html
            - /Users/funkyi/Desktop/Projects/Me/mssp-extensions:/usr/share/nginx/html
            # - /home/ec2-user/nginx:/usr/share/nginx/html
        ports:
            - 8001:80
            - 8002:443
        # depends_on:
        #     - node-app
        environment:
            SERVICE_NAME: app
            SERVICE_TAG: dev
        restart: unless-stopped
        networks:
            - extension-network

    # node-app:
    #     build: ./docker/node-app
    #     ports:
    #         - "3000:3000"
    #     networks:
    #         - extension-network
volumes:
  jenkins_data: 
  
networks:
    extension-network:
        driver: bridge
